### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by CanePlayz** [Deflopper/DiscordDataPackageAnalyser#1]
I'm sorry, but I'm not really into coding and all of that stuff. So what exactly do I have to download and run to use this program?

**Comment by Stijn-Jacobs** [comment]
You can download a release from the release tab (the .jar file). You'll need your discord privacy package, you can request that from privacy settings in Discord. Then unpack the .zip you get from discord and click the big open file button in my program. Then click load and you data should start loading. After that you can see all the graphs.

**Comment by CanePlayz** [comment]
Okay thanks
